### PR TITLE
Update dependencies using Jenkins bom

### PR DESCRIPTION
**Pull request by rsandell**
A binary incompatible change in JCasC caused some tests to fail when run with the PCT.
Recompiling the tests against newer JCasC version should solve the issue.
To alleviate some future problems with choosing versions of dependencies changed to using [Jenkins BOM](https://github.com/jenkinsci/bom).

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by rsandell** [comment]
The build failure is due to hard coded Jenkins version for Java 11. And there are now plugin dependencies that requires newer core than what was hardcoded for the build.

I've fixed the Jenkinsfile, but since I am not a maintainer Jenkins doesn't trust me and won't run that fix until it is on master.

**Comment by TobiX** [comment]
Hmm, I'm normally quite conservative with the required Jenkins version in my plugins... But I'm not to hung up on this aspect, so if this is necessary, we can go ahead with the update. I updated the Jenkinsfile in master, so if you update this PR the build should pass.

**Comment by rsandell** [comment]
I've been very conservative with my plugins as well in the past.
But there have been plenty of analysis done on the statistics in the community, and all the findings indicates that those users who upgrade the plugins are already on recent core versions and when they upgrade they upgrade everything, so being conservative with dependencies seems to be not necessary.

At least when I started caring less about being conservative I didn't get any complaints from my users. same for Mark when he did the same on the git plugin. FWIW.

**Comment by rsandell** [comment]
BTW I just released a fix in the script security plugin for the caffeine dependency problem. So the next bom version might not need the dependency management fix of the caffeine api.

**Comment by rsandell** [comment]
But it is your decision of course, I might be able to dig up exactly when the breaking change happened and try to back up the version requirements a little bit, but it might not be worth the effort :)

**Comment by TobiX** [comment]
Thanks!

**Comment by rsandell** [comment]
Thanks for merging @TobiX 
Any chance to get a release with this fix in? I would like an official release to start testing against to see if the PCT likes it or not :)

**Pull request merged**
