### PR TITLE
Jobs Grid portlet extension for convenient access to matrix build results

### PR DESCRIPTION
**Pull request by DominikGebhart**
As i heavily use matrix builds and quick overview which combination failed and build/log access is missing, i extended the jobs grid portlet with an option to display the most recent build results.

**I am not sure what's the best way to proceed to share this functionality.** This extension allows similar functionality as the Jobs Grid, options are
- replace Jobs Grid, update would break already configured Job Grids --> no go i guess.
- add this as separate portlet included in this plugin
- add this as separate portlet in a separate plugin

Idea for this emerged from http://stackoverflow.com/questions/36283079/show-multi-configuration-project-details-in-list-view

Screenshot of functionality is included there.

Any input is welcome.

### CODE REVIEW

**Comment by evandy0** [comment]
If this breaks the existing Jobs Grid Portlet, then I have to agree with you that it "isn't a great idea."   My initial reaction is that this is a great candidate to be split into its own plugin.   That said, I'm open to the argument of making it a separate view in this plugin, given sufficient reason.  Convince me.

**Comment by DominikGebhart** [comment]
Just to clarifyl, currently it just adds a portlet with the name 'Filtered Jobs Grid' to the list, so right now nothing breaks.

I think i will try if i get it to not break compat with the current 'Jobs Grid'. 

This extension shines only when you use matrix builds heavily.

**Comment by evandy0** [comment]
It it's mostly shining for those who use Matrix Builds, then leaving it as a separate portlet makes more sense to me...    it's either that, or make your enhancements configurable with on/off switches for everyone else.  I'll try and build it and check out your new view when I have a chance.

**Comment by DominikGebhart** [comment]
Thanks for your input, it already is configurable and the default setting behaves like the normal Job View, just the default column number is set to 1.

Settings look like this:
[![enter image description here][1]][1] 
If you want to give it a shot without compile, i got a hpi on [dropbox](https://www.dropbox.com/s/prp2i7mez95edzr/dashboard-view.hpi). 
If it feels wrong to add because of overlapping functionality, ill put it in a separate plugin. Just let me know.

  [1]: http://i.stack.imgur.com/mf5aa.png

**Comment by TobiX** [comment]
Hi, are you still interested in getting this merged?

**Comment by piotrsulej** [comment]
I find that one really useful and I am currently using compiled version provided by @DominikGebhart.  Having this merged into dashboard-view-plugin would be nice from my perspective as a user.

**Comment by TobiX** [comment]
This looks pretty self-contained to me, so packaging it as an additional plugin depending on dashboard-view should be pretty straightforward.

**Pull request closed without merging**
