### PR TITLE
upgrade to build with java 8

### PR DESCRIPTION
**Pull request by cburroughs**
Incidentally enables XSS protection along the way.

### CODE REVIEW

**Comment by cburroughs** [comment]
@daniel-beck per mailing list suggestion

**Comment by daniel-beck** [comment]
Should be reviewed by a maintainer who knows what gets shown in each of the views. @olivergondza maybe?

**Comment by olivergondza** [comment]
I do not see anything that seems to rely on not escaped behaviour. :+1:

**Comment by cburroughs** [comment]
Thanks for looking!

Given the +1 would someone kindly hit the merge button?

**Pull request merged**
